export const ActionTypes ={
    SET_PEOPLE : "SET_PEOPLE",
    UPDATE_EDIT_ITEM : "UPDATE_EDIT_ITEM",
    UPDATE_PEOPLE : "UPDATE_PEOPLE",
    UPDATE_ITEM : "UPDATE_ITEM",
    PUSH_SINGLE_ITEM : "PUSH_SINGLE_ITEM",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"
}