export const ActionTypes ={
    SET_PEOPLE : "SET_PEOPLE",
    UPDATE_EDIT_ITEM : "UPDATE_EDIT_ITEM",
    UPDATE_PEOPLE : "UPDATE_PEOPLE",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT"
}